s=(input('Digite algo '))
print('Tipo primitivo:',type(s))
print('Só te espaço:',s.isspace())
print('Alpha:',s.isalpha())
print('Numeric:',s.isnumeric())
print('Alpha numeric:',s.isalnum())
print('Conteúdo minúsculo:',s.islower())
print('Conteúdo maiúsculo:',s.isupper())
print('Conteúdo capitalizado:',s.istitle())
input('Aperte ENTER para finalizar')
