#GISELE
print('ATENÇÃO ESSE JOGO É UMA DEMO!')
print('O SEU OBJETIVO É DESCOBRIR QUEM É O CULPADO.')
print('VOCÊ É UM(A) POLICIAL E ESTÁ INTERROGANDO TRÊS SUSPEITOS:\n GISELE \n ALESSANDRA \n ADRIANA \n QUAL DELAS É A CULPADA?')
input('APERTE ENTER PARA COMEÇAR!')
n1=input('QUAL O SEU NOME? ')
print('HÁ TRÊS DIAS HOUVE UM ASSASINATO NA RUA BAKER STREET, AS INVESTIGAÇÕES LEVARAM A TRÊS SUSPEITAS: GISELE, ADRIANA, ALESSANDRA')
print('A VÍTIMA FOI UMA MODELO DE 29 ANOS SEU NOME ERA LAÍS, ELA ERA CASADA COM A SUSPEITA ADRIANA, MAS ERA SUSPEITO QUE ELA TIVESSE')
print('UM CASO COM GISELE, ALESSANDRA ERA SUA AGENTE, LAÍS FOI BALEADA DURANTE UM DESFILE A BALA ENTROU NO SEU PEITO ESQUERDO E SAIU')
print('PELAS COSTAS. NENHUMA DAS SUSPEITAS TINHA UMA ARMA, NÃO FOI ENCONTRADA NENHUM VIDEO QUE MOSTRASSE A ATIRADORA, MAS AS TRÊS SUSPEITAS')
print('ESTAVAM NO DESFILE E NENHUMA DELAS ESTAVA NA PLATEIA QUANDO O DISPARO FOI EFETUADO, O DESFILE FOI NO DIA 18 DE DEZEMBRO, ELA FOI MORTA AS 20:53.')
input('APERTE ENTER PARA CONTINUAR! ')
print('VOCÊ QUER INTERROGAR QUAL SUSPEITA PRIMEIRO? ')
print(' A) ALESSANDRA \n B) GISELE \n C) ADRIANA')
n2=input(' A, B, OU C? ')
if n2=='A':
    print('{}- BOA NOITE ALESSANDRA.'.format(n1))
    print('ALESSANDRA- BOA NOITE {}.'.format(n1))
    print('QUAL PERGUNTA VOCÊ QUER FAZER? ')
    print(' A) COMO VOCÊ CONHECIA LAÍS? \n B) ONDE VOCÊ ESTAVA QUANDO LAÍS FOI MORTA? \n C) VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?')
    a1=input('A, B, OU C? ')
    if a1=='A':
        print('{}- COMO VOCÊ CONHECIA A LAÍS?'.format(n1))
        print('ALESSANDRA- EU ERA A AGENTE DELA. EU NUNCA FARIA ALGUM MAL PARA ELA ERA A MINHA MELHOR MODELO.')
        print('{}- MAS UM ESCANDALO PODERIA ACABAR COM A CARREIRA DELA, COMO POR EXEMPLO UM CASO, ALÉM DISSO COM A MORTE ELA VIROU UMA LENDA \n ISSO MELHOROU OS SEUS GANHOS COM A IMAGEM DA LAÍS.'.format(n1))
        print('ALESSANDRA- VOCÊ ACHA MESMO QUE EU A MATARIA SÓ PARA MELHORAR MINHA CONTA BANCARIA VOCÊ SÓ PODE ESTAR BRINCANDO!')
        print('ALESSANDRA- UM CASO? DO QUE VOCÊ ESTÁ FALANDO? ELA AMAVA A ADRIANA.')
        print('{}- NÃO É OQUE DIZIAM PELOS CORREDORES, FALAVAM QUE ELA ESTAVA TENDO UM CASO COM A GISELE.'.format(n1))
        print('B) ONDE VOCÊ ESTAVA QUANDO LAÍS FOI MORTA? \n C) VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?')
        b1=input('B, OU C?')
        if b1=='B':
            print('{}- ONDE VOCÊ ESTAVA QUANDO A LAÍS FOI MORTA?'.format(n1))
            print('ALESSANDRA- ESTAVA NOS FUNDOS CUIDANDO DAS MINHAS OUTRAS MODELOS.')
            print('{}- AS CAMERAS MOSTRARAM VOCÊ NA PLATEIA POUCO ANTES DO TIRO.'.format(n1))
            print('{}- PARA ONDE VOCÊ FOI DEPOIS DE TER SAIDO DA PLATEIA?'.format(n1))
            print('ALESSANDRA- EU ESTAVA NA PLATEIA PORQUE ESTAVA ACOMPANHANDO O DESFILE, EU SAÍ PARA PREPARAR A LAÍS.')
        if b1=='C':
            print('VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?'.format(n1))
            print('ALESSANDRA- PARA FALAR A VERDADE NÃO, ELA ERA AMADA POR TODOS.')
            print('{}- ELA TINHA UMA BOA RELAÇÂO COM SUA ESPOSA?'.format(n1))
            print('ALESSANDRA- ELAS SEMPRE SE DERAM MUITO BEM, MAS RECENTEMENTE ANDARAM AFASTADAS, EU OUVI ELAS DISCUTINDO NO CAMARIM.')
            print('{}- SOBRE OQUE ERA A DISCUSSÃO?'.format(n1))
            print('ALESSANDRA- NÃO ESCUTEI DIREITO, MAS PARECE QUE ELAS QUERIAM SE SEPARAR.')
    if a1=='B':
        print('{}- ONDE VOCÊ ESTAVA QUANDO A LAÍS FOI MORTA?'.format(n1))
        print('ALESSANDRA- ESTAVA NOS FUNDOS CUIDANDO DAS MINHAS OUTRAS MODELOS.')
        print('{}- AS CAMERAS MOSTRARAM VOCÊ NA PLATEIA POUCO ANTES DO TIRO.'.format(n1))
        print('{}- PARA ONDE VOCÊ FOI DEPOIS DE TER SAIDO DA PLATEIA?'.format(n1))
        print('ALESSANDRA- EU ESTAVA NA PLATEIA PORQUE ESTAVA ACOMPANHANDO O DESFILE, EU SAÍ PARA PREPARAR A LAÍS.')
        print('A) COMO VOCÊ CONHECIA A LAÍS? C) VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?')
        c1=input('A, OU C?')
        if c1=='A':
            print('{}- COMO VOCÊ CONHECIA A LAÍS?'.format(n1))
            print('ALESSANDRA- EU ERA A AGENTE DELA. EU NUNCA FARIA ALGUM MAL PARA ELA ERA A MINHA MELHOR MODELO.')
            print(
                '{}- MAS UM ESCANDALO PODERIA ACABAR COM A CARREIRA DELA, COMO POR EXEMPLO UM CASO, ALÉM DISSO COM A MORTE ELA VIROU UMA LENDA \n ISSO MELHOROU OS SEUS GANHOS COM A IMAGEM DA LAÍS.'.format(
                    n1))
            print(
                'ALESSANDRA- VOCÊ ACHA MESMO QUE EU A MATARIA SÓ PARA MELHORAR MINHA CONTA BANCARIA VOCÊ SÓ PODE ESTAR BRINCANDO!')
            print('ALESSANDRA- UM CASO? DO QUE VOCÊ ESTÁ FALANDO? ELA AMAVA A ADRIANA.')
            print(
                '{}- NÃO É OQUE DIZIAM PELOS CORREDORES, FALAVAM QUE ELA ESTAVA TENDO UM CASO COM A GISELE.'.format(n1))
            print('B) ONDE VOCÊ ESTAVA QUANDO LAÍS FOI MORTA? \n C) VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?')
        if c1=='C':
            print('VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?'.format(n1))
            print('ALESSANDRA- PARA FALAR A VERDADE NÃO, ELA ERA AMADA POR TODOS.')
            print('{}- ELA TINHA UMA BOA RELAÇÂO COM SUA ESPOSA?'.format(n1))
            print(
                'ALESSANDRA- ELAS SEMPRE SE DERAM MUITO BEM, MAS RECENTEMENTE ANDARAM AFASTADAS, EU OUVI ELAS DISCUTINDO NO CAMARIM.')
            print('{}- SOBRE OQUE ERA A DISCUSSÃO?'.format(n1))
            print('ALESSANDRA- NÃO ESCUTEI DIREITO, MAS PARECE QUE ELAS QUERIAM SE SEPARAR.')
    if a1=='C':
        print('VOCÊ SABE DE ALGUÉM QUE QUISESSE MACHUCAR A LAÍS?'.format(n1))
        print('ALESSANDRA- PARA FALAR A VERDADE NÃO, ELA ERA AMADA POR TODOS.')
        print('{}- ELA TINHA UMA BOA RELAÇÂO COM SUA ESPOSA?'.format(n1))
        print('ALESSANDRA- ELAS SEMPRE SE DERAM MUITO BEM, MAS RECENTEMENTE ANDARAM AFASTADAS, EU OUVI ELAS DISCUTINDO NO CAMARIM.')
        print('{}- SOBRE OQUE ERA A DISCUSSÃO?'.format(n1))
        print('ALESSANDRA- NÃO ESCUTEI DIREITO, MAS PARECE QUE ELAS QUERIAM SE SEPARAR.')
        print('A) COMO VOCÊ CONHECIA LAÍS? \n B) ONDE VOCÊ ESTAVA QUANDO LAÍS FOI MORTA?')
        d1=input('A, OU B?')
        if d1=='A':
            print('{}- COMO VOCÊ CONHECIA A LAÍS?'.format(n1))
            print('ALESSANDRA- EU ERA A AGENTE DELA. EU NUNCA FARIA ALGUM MAL PARA ELA ERA A MINHA MELHOR MODELO.')
            print(
                '{}- MAS UM ESCANDALO PODERIA ACABAR COM A CARREIRA DELA, COMO POR EXEMPLO UM CASO, ALÉM DISSO COM A MORTE ELA VIROU UMA LENDA \n ISSO MELHOROU OS SEUS GANHOS COM A IMAGEM DA LAÍS.'.format(
                    n1))
            print(
                'ALESSANDRA- VOCÊ ACHA MESMO QUE EU A MATARIA SÓ PARA MELHORAR MINHA CONTA BANCARIA VOCÊ SÓ PODE ESTAR BRINCANDO!')
            print('ALESSANDRA- UM CASO? DO QUE VOCÊ ESTÁ FALANDO? ELA AMAVA A ADRIANA.')
            print(
                '{}- NÃO É OQUE DIZIAM PELOS CORREDORES, FALAVAM QUE ELA ESTAVA TENDO UM CASO COM A GISELE.'.format(n1))
        if d1=='B':
            print('{}- ONDE VOCÊ ESTAVA QUANDO A LAÍS FOI MORTA?'.format(n1))
            print('ALESSANDRA- ESTAVA NOS FUNDOS CUIDANDO DAS MINHAS OUTRAS MODELOS.')
            print('{}- AS CAMERAS MOSTRARAM VOCÊ NA PLATEIA POUCO ANTES DO TIRO.'.format(n1))
            print('{}- PARA ONDE VOCÊ FOI DEPOIS DE TER SAIDO DA PLATEIA?'.format(n1))
            print('ALESSANDRA- EU ESTAVA NA PLATEIA PORQUE ESTAVA ACOMPANHANDO O DESFILE, EU SAÍ PARA PREPARAR A LAÍS.')
if n2=='B':
input('APERTE ENTER PARA FINALIZAR!')

