print('OLÁ, SEJA BEM VINDO(A) AO PERGUNTAS LÓGICAS SEM LÓGICA!')
n1=input('QUAL O SEU NOME? ')
print('MUITO BEM {} ESSE JOGO VAI FUNCIONAR ASSIM:'.format(n1))
input('APERTE ENTER PARA VER AS REGRAS:')
print('REGRAS:')
print('1- NÃO VALE PESQUISAR.')
print('2- RESPONDA COM A LETRA A,B,C,D OU E QUE ACHAR ESTAR CERTA.')
print('3- DIVIRTA-SE.')
print('4- SAO 21 PERGUNTAS CASO A REPOSTA ESTEJA ERRADA O JOGO ACABA.')
print('5- AS RESPOSTAS DEVEM ESTAR EM MAIUSCULAS.')
print('BOA SORTE!')
input('APERTE ENTER PARA COMEÇAR:')
print('PRIMEIRA PERGUNDA:')
print('1# NORMALMENTE, QUANTOS LITROS DE SANGUE \n UMA PESSOA TEM? EM MEDIA, QUANTOS SAO \n RETIRADOS NUMA DOACAO DE SANGUE?')
print('A) 2 A 4 L, 450 ML')
print('B)4 A 6 L, 45O ML')
print('C) 10L, 2L')
print('D) 7L, 1.5L')
print('E) 0.5L, 0,5L')
n2=input('QUAL A SUA RESPOSTA? ')
if n2=='B':
    print('CERTA RESPOSTA!')
    input('APERTE ENTER PARA CONTINUAR!')
    print('SEGUNDA PERGUNTA:')
    print('2# DE QUEM E A FRASE "PENSO LOGO EXISTO"?')
    print('A) PLATAO')
    print('B) GALILEU GALILEI')
    print('C) DESCARTES')
    print('D) SOCRATES')
    print('E) TERRY CREWS')
    a1=input('QUAL A SUA RESPOSTA? ')
    if a1=='C':
        print('CERTA RESPOSTA!')
        input('APERTE ENTER PARA CONTINUAR!')
        print('TERCEIRA PERGUNTA:')
        print('3# DE ONDE E A INVENCAO DO CHUVEIRO ELETRICO?')
        print('A) FRANCA')
        print('B) INGLATERRA')
        print('C) BRASIL')
        print('D) AUSTRALIA')
        print('E) WAKANDA')
        b1=input('QUAL A SUA RESPOSTA? ')
        if b1=='C':
            print('CERTA RESPOSTA!')
            input('APERTE ENTER PARA CONTINUAR!')
            print('QUARTA PERGUNTA:')
            print('4# QUAL O MENOR E O MAIOR PAIS DO MUNDO?')
            print('A) VATICANO E RUSSIA')
            print('B) NAURU E CHINA')
            print('C) MALTA E ESTADOS UNIDOS')
            print('D) MONACO E CANADA')
            print('E) KRYPTON E BRASIL')
            c1=input('QUAL A SUA RESPOSTA? ')
            if c1=='A':
                print('CERTA RESPOSTA!')
                input('APERTE ENTER PARA CONTINUAR!')
                print('QUINTA PERGUNTA:')
                print('5# QUAL O NOME DO PRESIDENTE DO BRASIL QUE \n FICOU CONHECIDO COMO JANGO?')
                print('A) JANIO QUADROS')
                print('B) JACINTO ANJOS')
                print('C) JOAO FIGUEREDO')
                print('D) JOAO GULART')
                print('E) JAIR BOLSONARO')
                d1=input('QUAL A SUA RESPOSTA? ')
                if d1=='D':
                    print('CERTA RESPOSTA!')
                    input('APERTE ENTER PARA CONTINUAR!')
                    print('SEXTA PERGUNTA:')
                    print('6# QUAL O LIVRO MAIS VENDIDO NO MUNDO A \n SEGUIR A BIBLIA?')
                    print('A) O SENHOR DOS ANEIS')
                    print('B) DOM QUIXOTE')
                    print('C) O PEQUENO PRINCIPE')
                    print('D) ELA, A FEITICEIRA')
                    print('E) UM VAMPIRO NA CORTE DE DOM JOAO')
                    e1=input('QUAL A SUA RESPOSTA? ')
                    if e1=='B':
                        print('CERTA RESPOSTA!')
                        input('APERTE ENTER PARA CONTINUAR!')
                        print('SETIMA PERGUNTA')
                        print('7# QUANTAS CASAS DECIMAIS TEM O NUMERO PI?')
                        print('A) DUAS')
                        print('B) CENTENAS')
                        print('C) INFINITAS')
                        print('D) VINTE')
                        print('E) ZERO')
                        a7=input('QUAL A SUA RESPOSTA? ')
                        if a7=='C':
                            print('CERTA RESPOSTA!')
                            input('APERTE ENTER PARA CONTINUAR!')
                            print('OITAVA PERGUNTA')
                            print('8# ATUALMENTE, QUANTOS ELEMENTOS \n QUIMICOS A TABELA PERIODICA POSSUI?')
                            print('A) 113')
                            print('B) 109')
                            print('C) 108')
                            print('D) 118')
                            print('E) 1')
                            a8 = input('QUAL A SUA RESPOSTA? ')
                            if a8 == 'D':
                                print('CERTA RESPOSTA!')
                                input('APERTE ENTER PARA CONTINUAR!')
                                print('NONA PERGUNTA')
                                print('9# QUAIS OS PAISES QUE TEM A MAIOR E A \n MENOR EXPECTATIVA DE VIDA DO MUNDO?')
                                print('A) JAPAO E SERRA LEOA')
                                print('B) AUSTRALIA E AFEGANISTAO')
                                print('C) ITALIA E CHADE')
                                print('D) BRASIL E CONGO')
                                print('E) MARTE E MERCURIO')
                                a9 = input('QUAL A SUA RESPOSTA? ')
                                if a9 == 'A':
                                    print('CERTA RESPOSTA!')
                                    input('APERTE ENTER PARA CONTINUAR!')
                                    print('DECIMA PERGUNTA')
                                    print('10# OQUE A PALAVRA "LEGEND" SIGNIFICA EM PORTUGUES?')
                                    print('A) LEGENDA')
                                    print('B) CONTO')
                                    print('C) LENDA')
                                    print('D) HISTORIA')
                                    print('E) PIRULETA')
                                    a10 = input('QUAL A SUA RESPOSTA? ')
                                    if a10 == 'C':
                                        print('CERTA RESPOSTA!')
                                        input('APERTE ENTER PARA CONTINUAR!')
                                        print('PERGUNTA NUMERO 11')
                                        print('11# QUAL O NUMERO MINIMO DE JOGADORES \n NUMA PARTIDA DE FUTEBOL?')
                                        print('A) 8')
                                        print('B) 7')
                                        print('C) 9')
                                        print('D) 5')
                                        print('E) 0')
                                        a11 = input('QUAL A SUA RESPOSTA? ')
                                        if a11 == 'B':
                                            print('CERTA RESPOSTA!')
                                            input('APERTE ENTER PARA CONTINUAR!')
                                            print('PERGUNTA NUMERO 12')
                                            print('12# QUAIS OS PRINCIPAIS AUTORES DO BARROCO \n NO BRASIL?')
                                            print('A) GREGORIO DE MATOS, BENTO TEIXEIRA EMANUEL BOTELHO DE OLIVEIRA')
                                            print('B) MIGUEL CERVANTES, GREGORIO DE MATOS E DANTHE ALIGHIERI')
                                            print('C) PADRE ANTONIO VIEIRA, PADRE MANUEL MELO E GREGORIO MATOS')
                                            print('D) CASTRO ALVES, BENTO TEIXEIRA E MANUEL DE MELO GREGORIO DE MATOS')
                                            print('E) PADRE FABIO DE MELO, LARISSA DE MACEDO MACHADO E PELE')
                                            a12 = input('QUAL A SUA RESPOSTA? ')
                                            if a12 == 'A':
                                                print('CERTA RESPOSTA!')
                                                input('APERTE ENTER PARA CONTINUAR!')
                                                print('PERGUNTA NUMERO 13')
                                                print('13# QUAIS AS DUAS DATAS QUE SAO \n COMEMORADAS EM NOVEMBRO?')
                                                print('A) INDEPENDENCIA DO BRASIL E DIA DA BANDEIRA')
                                                print('B) PROCLAMACAO DA REPUBLICA E DIA NASCIONAL DA CONSCIENCIA NEGRA')
                                                print('C) DIA DO MEDICO E DIA DE SAO LUCAS')
                                                print('D) DIA DE FINADOS E DIA NACIONAL DO LIVRO')
                                                print('E) MEU ANIVERSARIO E PASCOA')
                                                a13 = input('QUAL A SUA RESPOSTA? ')
                                                if a13 == 'B':
                                                    print('CERTA RESPOSTA!')
                                                    input('APERTE ENTER PARA CONTINUAR!')
                                                    print('PERGUNTA NUMERO 14')
                                                    print('14# QUEM PINTOU A "GUERNICA"?')
                                                    print('A) DA VINCCI')
                                                    print('B) PABLO PICASSO')
                                                    print('C) VAN GOGH')
                                                    print('D) SALVADOR DALI')
                                                    print('E) TARCILA DO AMARAL')
                                                    a14 = input('QUAL A SUA RESPOSTA? ')
                                                    if a14 == 'B':
                                                        print('CERTA RESPOSTA!')
                                                        input('APERTE ENTER PARA CONTINUAR!')
                                                        print('PERGUNTA NUMERO 15')
                                                        print('15# QUANTO TEMPO A LUZ DO SOL DEMORA PARA \n CHEGAR A TERRA?')
                                                        print('A) 12 MINUTOS')
                                                        print('B) 1 DIA')
                                                        print('C) 12 HORAS')
                                                        print('D) 8 MINUTOS')
                                                        print('E) PI SEGUNDOS')
                                                        a15 = input('QUAL A SUA RESPOSTA? ')
                                                        if a15 == 'D':
                                                            print('CERTA RESPOSTA!')
                                                            input('APERTE ENTER PARA CONTINUAR!')
                                                            print('PERGUNTA NUMERO16')
                                                            print('16# QUAL A TRADUCAO DA FRASE "FABIANO COGIO \n SU SACO ANTES DE SALIR"?')
                                                            print('A) FABIANO COSEU SEU PALETO ANTES DE SAIR')
                                                            print('B) FABIANO FECHOU O SACO ANTES DE SAIR')
                                                            print('C) FABIANO PEGOU SEU PALETO ANTES DE SAIR')
                                                            print('D) FABIANO CORTOU O SACO ANTES DE SAIR')
                                                            print('E) FABIANO E O VELHO DO SACO ELE VAI TE PEGAR')
                                                            a16 = input('QUAL A SUA RESPOSTA? ')
                                                            if a16 == 'C':
                                                                print('CERTA RESPOSTA!')
                                                                input('APERTE ENTER PARA CONTINUAR!')
                                                                print('PERGUNTA NUMERO 17')
                                                                print('17# QUAL A NACIONALIDADE DE CHE GUEVARA? ')
                                                                print('A) ARGENTINA')
                                                                print('B) PERUANA')
                                                                print('C) PANAMENHA')
                                                                print('D) BOLIVIANA')
                                                                print('E) WAKANDANO')
                                                                a17 = input('QUAL A SUA RESPOSTA? ')
                                                                if a17 == 'A':
                                                                    print('CERTA RESPOSTA!')
                                                                    input('APERTE ENTER PARA CONTINUAR!')
                                                                    print('PERGUNTA NUMERO 18')
                                                                    print('18# QUAIS SAO OS TRES PREDADORES DO REINO \n ANIMAL RECONHECIDOS PELA HABILIDADE DE \n CACAR EM GRUPO, SE CAMUFLAR PARA \n SURPREENDER AS PRESAS E POSSUIR SENTIDOS \n APURADOS, RESPECTIVAMENTE:')
                                                                    print('A) TUBARAO BRANCO, CROCODILO E SUCURI')
                                                                    print('B) TIGRE, GAVIAO E ORCA')
                                                                    print('C) HIENA, URSO BRANCO, LOBO CINZENTO')
                                                                    print('D) ORCA, ONCA E TARANTULA')
                                                                    print('E) SIMBA, DORI E LULA MOLUSCO')
                                                                    a18 = input('QUAL A SUA RESPOSTA? ')
                                                                    if a18 == 'C':
                                                                        print('CERTA RESPOSTA!')
                                                                        input('APERTE ENTER PARA CONTINUAR!')
                                                                        print('PERGUNTA NUMERO 19')
                                                                        print('19# QUAL A ALTURA DA REDE DE VOLEI NOS JOGOS \n MASCULINOS E FEIMININO?')
                                                                        print('A) 2.43 M E 2.24 M')
                                                                        print('B) 2.5 M E 2.0 M')
                                                                        print('C) 1.8 M E 1.5 M')
                                                                        print('D) 2.4 M PARA AMBOS')
                                                                        print('E) 0.5 M E 10 M')
                                                                        a19 = input('QUAL A SUA RESPOSTA? ')
                                                                        if a19 == 'A':
                                                                            print('CERTA RESPOSTA!')
                                                                            input('APERTE ENTER PARA CONTINUAR!')
                                                                            print('PERGUNTA NUMERO 20')
                                                                            print('20# EM QUAL QUESTAO EU COMECEI A FALAR "QUESTAO \n DE NUMERO ..."?')
                                                                            print('A) 11')
                                                                            print('B) 12')
                                                                            print('C) 5')
                                                                            print('D) 9')
                                                                            print('E) JA COMECOU ASSIM')
                                                                            a20 = input('QUAL A SUA RESPOSTA? ')
                                                                            if a20 == 'A':
                                                                                print('CERTA RESPOSTA!')
                                                                                input('APERTE ENTER PARA CONTINUAR!')
                                                                                print('PERGUNTA NUMERO 20')
                                                                                print('21# EM QUAL QUESTAO EU NAO COLOQUEI A "#" AO LADO DO NUMERO DA PERGUNTA?')
                                                                                print('A) 5')
                                                                                print('B) 11')
                                                                                print('C) 7')
                                                                                print('D) 18')
                                                                                print('E) NENHUMA')
                                                                                a21 = input('QUAL A SUA RESPOSTA? ')
                                                                                if a21 == 'E':
                                                                                    print('CERTA RESPOSTA!')
                                                                                    input('APERTE ENTER PARA CONTINUAR!')
                                                                                    print('MEUS PARABÉNS VOCES FINALIZARAM QUANTA INTELIGENCIA!')
                                                                                else:
                                                                                    print('ERROU!!!')
                                                                            else:
                                                                                print('ERROU!!!')
                                                                        else:
                                                                            print('ERROU!!!')
                                                                    else:
                                                                        print('ERROU!!!')
                                                                else:
                                                                    print('ERROU!!!')
                                                            else:
                                                                print('ERROU!!!')
                                                        else:
                                                            print('ERROU!!!')
                                                    else:
                                                        print('ERROU!!!')
                                                else:
                                                    print('ERROU!!!')
                                            else:
                                                print('ERROU!!!')
                                        else:
                                            print('ERROU!!!')
                                    else:
                                        print('ERROU!!!')
                                else:
                                    print('ERROU!!!')
                            else:
                                print('ERROU!!!')
                        else:
                            print('ERROU!!!')
                    else:
                        print('ERROU!!!')
                else:
                    print('ERROU!!!')
            else:
                print('ERROU!!!')
    else:
        print('ERROU!!!')
else:
    print('ERROU!!!')
input('APERTE ENTER PARA FINALIZAR!')
